name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Test
          run: |
            docker run \
              -v ${{github.workspace}}:/test \
              --entrypoint "/bin/sh" \
              --rm \
              ianwalter/puppeteer:v4.0.0 \
              -c "cd /test && npm install && npm run test:local"
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs

